import { defineConfig } from "vite";
import preact from "@preact/preset-vite";
import { viteSingleFile } from "vite-plugin-singlefile";
import fs from "node:fs";
import path from "node:path";

function renderHelpTextsFile(data) {
  const normalized = {
    permissions: data.permissions ?? {},
    permissionNames: data.permissionNames ?? {},
    menuOverrides: data.menuOverrides ?? {},
    menuDescriptions: data.menuDescriptions ?? {},
  };
  return `// auto-generated by dev editor — do not edit manually\nexport const HELP_TEXTS = ${JSON.stringify(normalized, null, 2)}\n`;
}

function renderGlossaryFile(data) {
  return `// auto-generated by dev editor — do not edit manually\nexport const GLOSSARY = ${JSON.stringify(data, null, 2)}\n`;
}

function renderMenusFile(data) {
  return JSON.stringify(data, null, 2) + "\n";
}

// 실데이터(menus.json 등)는 gitignore 대상이라 저장소를 새로 pull하면 존재하지 않는다.
// 이 경우에만 같은 이름의 .sample 파일을 복사해 생성해서, 클론 직후에도 빈 화면 대신
// 가짜(샘플) 데이터로 앱이 바로 동작하게 한다. 실파일이 이미 있으면 손대지 않는다.
const SAMPLE_DATA_FILES = [
  ["src/data/menus.json", "src/data/menus.sample.json"],
  ["src/data/shortcuts.js", "src/data/shortcuts.sample.js"],
  ["src/data/glossary.js", "src/data/glossary.sample.js"],
  ["src/data/helpTexts.js", "src/data/helpTexts.sample.js"],
  ["src/data/contact.js", "src/data/contact.sample.js"],
];

function sampleDataBootstrap() {
  return {
    name: "sample-data-bootstrap",
    config() {
      for (const [real, sample] of SAMPLE_DATA_FILES) {
        const realPath = path.resolve(real);
        const samplePath = path.resolve(sample);
        if (!fs.existsSync(realPath) && fs.existsSync(samplePath)) {
          fs.copyFileSync(samplePath, realPath);
          console.log(`[sample-data-bootstrap] ${real} 없음 → ${sample}에서 복사함`);
        }
      }
    },
  };
}

function helpTextWriter() {
  return {
    name: "help-text-writer",
    apply: "serve",
    configureServer(server) {
      server.middlewares.use("/__write-help-texts", async (req, res) => {
        if (req.method !== "POST") {
          res.statusCode = 405;
          return res.end("Method Not Allowed");
        }
        try {
          const chunks = [];
          for await (const chunk of req) chunks.push(chunk);
          const data = JSON.parse(Buffer.concat(chunks).toString("utf-8"));

          const file = path.resolve("src/data/helpTexts.js");
          fs.writeFileSync(file, renderHelpTextsFile(data), "utf-8");

          res.statusCode = 200;
          res.setHeader("Content-Type", "application/json");
          res.end(JSON.stringify({ ok: true }));
        } catch (e) {
          console.error("[help-text-writer]", e);
          res.statusCode = 500;
          res.setHeader("Content-Type", "application/json");
          res.end(JSON.stringify({ error: String(e) }));
        }
      });

      server.middlewares.use("/__write-shortcuts", async (req, res) => {
        if (req.method !== "POST") {
          res.statusCode = 405;
          return res.end("Method Not Allowed");
        }
        try {
          const chunks = [];
          for await (const chunk of req) chunks.push(chunk);
          const data = JSON.parse(Buffer.concat(chunks).toString("utf-8"));

          const file = path.resolve("src/data/shortcuts.js");
          const content = `// auto-generated by dev editor — do not edit manually\nexport const SHORTCUTS = ${JSON.stringify(data, null, 2)}\n`;
          fs.writeFileSync(file, content, "utf-8");

          res.statusCode = 200;
          res.setHeader("Content-Type", "application/json");
          res.end(JSON.stringify({ ok: true }));
        } catch (e) {
          console.error("[help-text-writer]", e);
          res.statusCode = 500;
          res.setHeader("Content-Type", "application/json");
          res.end(JSON.stringify({ error: String(e) }));
        }
      });

      server.middlewares.use("/__write-glossary", async (req, res) => {
        if (req.method !== "POST") {
          res.statusCode = 405;
          return res.end("Method Not Allowed");
        }
        try {
          const chunks = [];
          for await (const chunk of req) chunks.push(chunk);
          const data = JSON.parse(Buffer.concat(chunks).toString("utf-8"));

          const file = path.resolve("src/data/glossary.js");
          fs.writeFileSync(file, renderGlossaryFile(data), "utf-8");

          res.statusCode = 200;
          res.setHeader("Content-Type", "application/json");
          res.end(JSON.stringify({ ok: true }));
        } catch (e) {
          console.error("[help-text-writer]", e);
          res.statusCode = 500;
          res.setHeader("Content-Type", "application/json");
          res.end(JSON.stringify({ error: String(e) }));
        }
      });
      server.middlewares.use("/__write-menus", async (req, res) => {
        if (req.method !== "POST") {
          res.statusCode = 405;
          return res.end("Method Not Allowed");
        }
        try {
          const chunks = [];
          for await (const chunk of req) chunks.push(chunk);
          const data = JSON.parse(Buffer.concat(chunks).toString("utf-8"));

          const file = path.resolve("src/data/menus.json");
          fs.writeFileSync(file, renderMenusFile(data), "utf-8");

          res.statusCode = 200;
          res.setHeader("Content-Type", "application/json");
          res.end(JSON.stringify({ ok: true }));
        } catch (e) {
          console.error("[help-text-writer]", e);
          res.statusCode = 500;
          res.setHeader("Content-Type", "application/json");
          res.end(JSON.stringify({ error: String(e) }));
        }
      });
    },
  };
}

export default defineConfig({
  plugins: [preact(), viteSingleFile(), sampleDataBootstrap(), helpTextWriter()],
  build: {
    reportCompressedSize: true,
  },
});
