import { defineConfig } from "vite";
import preact from "@preact/preset-vite";
import { viteSingleFile } from "vite-plugin-singlefile";
import fs from "node:fs";
import path from "node:path";

function renderHelpTextsFile(data) {
  const normalized = {
    permissions: data.permissions ?? {},
    permissionNames: data.permissionNames ?? {},
    menuOverrides: data.menuOverrides ?? {},
    menuDescriptions: data.menuDescriptions ?? {},
    menuTitles: data.menuTitles ?? {},
  };
  return `// auto-generated by dev editor — do not edit manually\nexport const HELP_TEXTS = ${JSON.stringify(normalized, null, 2)}\n`;
}

function renderGlossaryFile(data) {
  return `// auto-generated by dev editor — do not edit manually\nexport const GLOSSARY = ${JSON.stringify(data, null, 2)}\n`;
}

function renderMenusFile(data) {
  return JSON.stringify(data, null, 2) + "\n";
}

// 실데이터(menus.json 등)는 gitignore 대상이라 저장소를 새로 pull하면 존재하지 않는다.
// dev:sample(DEV_SAMPLE=1) 구동 중에는 아래 목록의 실데이터 경로로 들어오는 import를
// 빌드 타임에 .sample 파일로 "바꿔치기"해서 해석한다 — 실데이터 파일은 절대 복사·수정·삭제하지
// 않는다(파일이 아예 없어도 동작함). 과거 실데이터 파일에 샘플 내용을 물리적으로 덮어썼다가
// 복원에 실패해 실데이터를 영구히 잃은 사고가 있었기 때문에, 실데이터 경로의 파일 시스템 쓰기는
// 이 프로젝트에서 절대 금지 사항이다.
const SAMPLE_DATA_FILES = [
  ["src/data/menus.json", "src/data/menus.sample.json"],
  ["src/data/shortcuts.js", "src/data/shortcuts.sample.js"],
  ["src/data/glossary.js", "src/data/glossary.sample.js"],
  ["src/data/helpTexts.js", "src/data/helpTexts.sample.js"],
  ["src/data/contact.js", "src/data/contact.sample.js"],
];

const IS_SAMPLE_MODE = process.env.DEV_SAMPLE === "1";

// import "./data/menus.json" 등이 실제로 가리키는 절대 경로를 계산해, 샘플 모드일 때만
// 그 자리에서 .sample 파일의 절대 경로로 리졸브 결과를 바꿔치기한다(디스크 쓰기 없음).
function sampleDataResolver() {
  if (!IS_SAMPLE_MODE) return { name: "sample-data-resolver:noop" };
  const realAbsPaths = SAMPLE_DATA_FILES.map(([real, sample]) => [
    path.resolve(real),
    path.resolve(sample),
  ]);
  return {
    name: "sample-data-resolver",
    enforce: "pre",
    resolveId(source, importer) {
      if (!importer) return null;
      const resolved = path.resolve(path.dirname(importer), source);
      const hit = realAbsPaths.find(([realAbs]) => realAbs === resolved);
      return hit ? hit[1] : null;
    },
  };
}

// 샘플 모드에서 편집 내용을 저장할 때도 .sample 파일에만 쓴다(실데이터 경로는 절대 건드리지 않음).
// 같은 세션 안의 화면 반영은 EditApp.jsx가 저장 성공 후 메모리 내 객체를 직접 mutate해서 처리하므로,
// 디스크에 남기는 건 다음 실행을 위한 영속화 목적뿐이라 .sample 파일 하나에만 써도 충분하다.
function writeDataFile(realPath, render, data) {
  const content = render(data);
  if (IS_SAMPLE_MODE) {
    const [, samplePath] = SAMPLE_DATA_FILES.find(([r]) => r === realPath);
    fs.writeFileSync(path.resolve(samplePath), content, "utf-8");
    return;
  }
  fs.writeFileSync(path.resolve(realPath), content, "utf-8");
}

function helpTextWriter() {
  return {
    name: "help-text-writer",
    apply: "serve",
    configureServer(server) {
      server.middlewares.use("/__write-help-texts", async (req, res) => {
        if (req.method !== "POST") {
          res.statusCode = 405;
          return res.end("Method Not Allowed");
        }
        try {
          const chunks = [];
          for await (const chunk of req) chunks.push(chunk);
          const data = JSON.parse(Buffer.concat(chunks).toString("utf-8"));

          writeDataFile("src/data/helpTexts.js", renderHelpTextsFile, data);

          res.statusCode = 200;
          res.setHeader("Content-Type", "application/json");
          res.end(JSON.stringify({ ok: true }));
        } catch (e) {
          console.error("[help-text-writer]", e);
          res.statusCode = 500;
          res.setHeader("Content-Type", "application/json");
          res.end(JSON.stringify({ error: String(e) }));
        }
      });

      server.middlewares.use("/__write-shortcuts", async (req, res) => {
        if (req.method !== "POST") {
          res.statusCode = 405;
          return res.end("Method Not Allowed");
        }
        try {
          const chunks = [];
          for await (const chunk of req) chunks.push(chunk);
          const data = JSON.parse(Buffer.concat(chunks).toString("utf-8"));

          const render = d => `// auto-generated by dev editor — do not edit manually\nexport const SHORTCUTS = ${JSON.stringify(d, null, 2)}\n`;
          writeDataFile("src/data/shortcuts.js", render, data);

          res.statusCode = 200;
          res.setHeader("Content-Type", "application/json");
          res.end(JSON.stringify({ ok: true }));
        } catch (e) {
          console.error("[help-text-writer]", e);
          res.statusCode = 500;
          res.setHeader("Content-Type", "application/json");
          res.end(JSON.stringify({ error: String(e) }));
        }
      });

      server.middlewares.use("/__write-glossary", async (req, res) => {
        if (req.method !== "POST") {
          res.statusCode = 405;
          return res.end("Method Not Allowed");
        }
        try {
          const chunks = [];
          for await (const chunk of req) chunks.push(chunk);
          const data = JSON.parse(Buffer.concat(chunks).toString("utf-8"));

          writeDataFile("src/data/glossary.js", renderGlossaryFile, data);

          res.statusCode = 200;
          res.setHeader("Content-Type", "application/json");
          res.end(JSON.stringify({ ok: true }));
        } catch (e) {
          console.error("[help-text-writer]", e);
          res.statusCode = 500;
          res.setHeader("Content-Type", "application/json");
          res.end(JSON.stringify({ error: String(e) }));
        }
      });
      server.middlewares.use("/__write-menus", async (req, res) => {
        if (req.method !== "POST") {
          res.statusCode = 405;
          return res.end("Method Not Allowed");
        }
        try {
          const chunks = [];
          for await (const chunk of req) chunks.push(chunk);
          const data = JSON.parse(Buffer.concat(chunks).toString("utf-8"));

          writeDataFile("src/data/menus.json", renderMenusFile, data);

          res.statusCode = 200;
          res.setHeader("Content-Type", "application/json");
          res.end(JSON.stringify({ ok: true }));
        } catch (e) {
          console.error("[help-text-writer]", e);
          res.statusCode = 500;
          res.setHeader("Content-Type", "application/json");
          res.end(JSON.stringify({ error: String(e) }));
        }
      });
    },
  };
}

export default defineConfig({
  plugins: [preact(), viteSingleFile(), sampleDataResolver(), helpTextWriter()],
  build: {
    reportCompressedSize: true,
  },
});
